export const filtersBefore = [
    { name: "free", className: "fa-solid fa-bolt", available: "2016" },
    { name: "New In V6", className: "fa-solid fa-star", available: "8336" },
    { name: "Sponsered", className: "fa-solid fa-dollar-sign", available: "3111", },
    { name: "Saff Favorites", className: "fa-solid fa-heart", available: "571", },
];


export const filtersAfter = [
    { name: "Accessibility", className: "fa-solid fa-person", available: "176" },
    { name: "Alert", className: "fa-solid fa-bell", available: "240" },
    { name: "Alphabet", className: "fa-solid fa-a", available: "390" },
    { name: "Animals", className: "fa-solid fa-cat", available: "305" },
    { name: "Arrows", className: "fa-solid fa-square-arrow-up-right", available: "1175" },
    { name: "Astronomy", className: "fa-solid fa-meteor", available: "120" },
    { name: "Automotive", className: "fa-solid fa-car-side", available: "355" },
    // { name: "Beverages", className: "fa-solid fa-champagne-glasses", available: "1175" },
    { name: "Buildings", className: "fa-solid fa-building-columns", available: "515" },
    { name: "Buisness", className: "fa-solid fa-briefcase", available: "830" },
    { name: "Camping", className: "fa-solid fa-campground", available: "325" },
    { name: "Charity", className: "fa-solid fa-hand-holding-heart", available: "180" },
    { name: "Charts + Diagrams", className: "fa-solid fa-chart-simple", available: "200" },
    { name: "Childhood", className: "fa-solid fa-baseball-bat-ball", available: "305" },
    { name: "Clothing + Fashion", className: "fa-solid fa-shirt", available: "160" },
    { name: "Coding", className: "fa-solid fa-code", available: "401" },
    { name: "Communication", className: "fa-solid fa-comment-dots", available: "621" },
    { name: "Connectivity", className: "fa-solid fa-signal", available: "201" },
    { name: "Construction", className: "fa-solid fa-person-digging", available: "255" },
    { name: "Design", className: "fa-solid fa-palette", available: "551" },
    { name: "Devices + Hardware", className: "fa-solid fa-computer", available: "450" },
    { name: "Disaster + Crisis", className: "fa-solid fa-burst", available: "200" },
    { name: "Editing", className: "fa-solid fa-pen-to-square", available: "660" },
    { name: "Education", className: "fa-solid fa-graduation-cap", available: "205" },
    { name: "Emoji", className: "fa-solid fa-face-grin", available: "550" },
    { name: "Energy", className: "fa-solid fa-bolt", available: "360" },
    { name: "Files", className: "fa-solid fa-copy", available: "325" },
    { name: "Film + Video", className: "fa-solid fa-film", available: "401" },
    { name: "Food", className: "fa-solid fa-burger", available: "715" },
    { name: "Fruits + Vegetables", className: "fa-solid fa-apple-whole", available: "225" },
    { name: "Gaming", className: "fa-solid fa-gamepad", available: "521" },
    { name: "Genders", className: "fa-solid fa-venus-mars", available: "70" },
    { name: "Halloween", className: "fa-solid fa-hat-wizard", available: "195" },
    { name: "Hands", className: "fa-solid fa-hand", available: "265" },
    { name: "Holidays", className: "fa-solid fa-sleigh", available: "225" },
    { name: "Household", className: "fa-solid fa-house-chimney-window", available: "740" },
    { name: "Humanitarian", className: "fa-solid fa-parachute-box", available: "1665" },
    { name: "Logistics", className: "fa-solid fa-truck-fast", available: "460" },
    { name: "Maps", className: "fa-solid fa-map-location", available: "900" },
    { name: "Mearitime", className: "fa-solid fa-anchor", available: "135" },
    { name: "Marketing", className: "fa-solid fa-bullhorn", available: "260" },
    { name: "Mathematics", className: "fa-solid fa-calculator", available: "280" },
    { name: "Media Playback", className: "fa-solid fa-forward-fast", available: "240" },
    { name: "Medical + Health", className: "fa-solid fa-briefcase-medical", available: "751" },
    { name: "Money", className: "fa-solid fa-money-bill-1-wave", available: "480" },
       { name: "Moving", className: "fa-solid fa-dolly", available: "185" },
     { name: "Music + Audio", className: "fa-solid fa-music", available: "443" },
    { name: "Nature", className: "fa-solid fa-mountain-sun", available: "250" },
    { name: "Numbers", className: "fa-solid fa-2", available: "160" },
    { name: "Photo + Images", className: "fa-solid fa-camera-retro", available: "286" },
    { name: "Political", className: "fa-solid fa-check-double", available: "165" },
      { name: "Punctuation + Symbols", className: "fa-solid fa-quote-left", available: "245" },
    { name: "Religion", className: "fa-solid fa-person-praying", available: "175" },
    { name: "Science", className: "fa-solid fa-atom", available: "225" },
    { name: "Science Fiction", className: "fa-solid fa-robot", available: "250" },
    { name: "Security", className: "fa-solid fa-shield", available: "490" },
    //    { name: "Shapes", className: "fa-solid fa-shield", available: "265" },
    { name: "Shopping", className: "fa-solid fa-cart-shopping", available: "458" },
    { name: "Social", className: "fa-solid fa-hashtag", available: "210" },
    //   { name: "Spinners", className: "fa-solid fa-heart-pulse", available: "175" },
    { name: "Sports + Fitness", className: "fa-solid fa-heart-pulse", available: "380" },
    { name: "Text Formatting", className: "fa-solid fa-underline", available: "405" },
    { name: "Time", className: "fa-solid fa-calendar-days", available: "380" },
    { name: "Toggle", className: "fa-solid fa-toggle-on", available: "240" },
    { name: "Transportation", className: "fa-solid fa-truck-plane", available: "451" },
    { name: "Travel", className: "fa-solid fa-caravan", available: "675" },
    { name: "Users", className: "fa-solid fa-person", available: "996" },
    { name: "Weather", className: "fa-solid fa-cloud-sun", available: "395" },
    { name: "Writing", className: "fa-solid fa-file-pen", available: "305" },
];